import { GoogleGenAI } from "@google/genai";

export interface AIProviderRequest {
  systemPrompt?: string;
  prompt: string;
  temperature?: number;
  history?: Array<{ role: string; content: string }>;
  model?: string;
  taskType?: 'wordpress_plugin' | 'php' | 'javascript' | 'architecture' | 'security' | 'general';
}

export interface AIProviderResponse {
  reply: string;
  providerUsed: 'ollama' | 'lmstudio' | 'gemini' | 'openrouter';
  modelUsed: string;
  tokensEstimated?: number;
}

export class AIProviderService {
  private static ollamaHost = process.env.OLLAMA_HOST || "http://localhost:11434";

  /**
   * Execute chat via local Ollama endpoint (OpenAI compatible / native)
   */
  public static async callOllama(req: AIProviderRequest, modelName: string = "qwen2.5-coder:7b"): Promise<string> {
    const url = `${this.ollamaHost}/v1/chat/completions`;
    
    const messages: Array<{ role: string; content: string }> = [];
    if (req.systemPrompt) {
      messages.push({ role: "system", content: req.systemPrompt });
    }
    if (req.history) {
      req.history.forEach((m) => messages.push({ role: m.role, content: m.content }));
    }
    messages.push({ role: "user", content: req.prompt });

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 15000); // 15s timeout for local ping/fallback

    try {
      const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        signal: controller.signal,
        body: JSON.stringify({
          model: modelName,
          messages,
          temperature: req.temperature ?? 0.7,
        }),
      });

      clearTimeout(timeout);

      if (!res.ok) {
        throw new Error(`Ollama HTTP ${res.status}: ${res.statusText}`);
      }

      const data = await res.json();
      return data.choices?.[0]?.message?.content || "No response generated by local model.";
    } catch (err: any) {
      clearTimeout(timeout);
      throw new Error(`Ollama unreachable or timed out (${err.message})`);
    }
  }

  /**
   * Execute chat via Google Gemini AI
   */
  public static async callGemini(req: AIProviderRequest, apiKey: string): Promise<string> {
    const ai = new GoogleGenAI({ apiKey });
    const selectedModel = req.model || "gemini-3.6-flash";

    const contents: Array<{ role: string; parts: Array<{ text: string }> }> = [];

    if (req.history) {
      req.history.forEach((msg) => {
        contents.push({
          role: msg.role === "assistant" ? "model" : "user",
          parts: [{ text: msg.content }],
        });
      });
    }

    contents.push({
      role: "user",
      parts: [{ text: req.prompt }],
    });

    const response = await ai.models.generateContent({
      model: selectedModel,
      contents,
      config: {
        systemInstruction: req.systemPrompt || "You are an expert AI Engineering Assistant specializing in WordPress and software architecture.",
        temperature: req.temperature ?? 0.7,
      },
    });

    return response.text || "No response generated by Gemini.";
  }
}
